### ISSUE TITLE
Hwyla Format Error

### ISSUE THREAD

**Issue by WenXin20** [TheMCBrothers/Interior-Mod#1]
Minecraft v1.14.4
Forge v28.1.61
Interior v1.1.0
Hwyla v1.10.6-B67

Currently, the text for all tables and chairs display a format error of `%s Chair` and `%s Table`

![2019-10-21_14 29 09](https://user-images.githubusercontent.com/12000593/67237559-24c4a800-f411-11e9-85ef-1a93b6825136.png)

**Comment by TheMCBrothers-Manager** [comment]
Thanks for reporting this issue.
I will fix this issue in the next version of the mod
