### ISSUE TITLE
1.15.2- [Caused by: java.lang.RuntimeException: Attempted to load class net/minecraftforge/resource/ReloadRequirements for invalid dist DEDICATED_SERVER]

### ISSUE THREAD

**Issue by SDUBZ** [TheMCBrothers/Interior-Mod#3]
This happens server side and can stoop other mods working correctly server side
Forge:1.15.2-31.1.18
Int: interiormod-1.15.2-1.2.1

logs:
[latest.log](https://github.com/TheMCBrothers/Interior-Mod/files/4303598/latest.log)

[debug.log](https://github.com/TheMCBrothers/Interior-Mod/files/4303597/debug.log)

**Comment by ProsperCraft** [comment]
Same problem with forge .30
interiormod-1.15.2-1.2.2.jar

https://gist.github.com/ProsperCraft/b48a9e6a0b7ccd5d0e47f7a111e60eec

**Comment by TheMCBrothers-Manager** [comment]
We hope that this problem never occurs again.
